#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PS7Bz235TsIFeD36JNXSx8oHmOWb9ALQcej0"
APP_SECRET: "Gj//IvTPKGAtnzagnZjH7YcyEz6RrzSbcfUSIv7IAGy8Hak32/xAWXz/lzxHTJt743LShP/LdtLA98vLoNeYxjZCgE1ze7EEVO+qEkUdymZcwNw11VPXHg12Xy8tb8Lf/E2qJtHuFwsIDXWm2wSKnKmLrF1gDYSVWExMG7FNOHL521DfGdc="

#계좌번호 앞 8자리
CANO: "63573756"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1055120678086529074/vwKYAcp1IPfSNFKuLfuDz2A_jvRB-0mnbG95jSprbLNtyrHZmjVKCdIacjbaaiERT3_Y"